# Generated by Django 6.1.1 on 2026-09-20 03:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='theaters.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked')], db_index=True, default='AVAILABLE', max_length=20)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='theaters.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='theaters.show')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='bookings.booking')),
                ('show_seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_seats', to='bookings.showseat')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-created_at'], name='bookings_bo_user_id_6151bb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['show', 'status'], name='bookings_bo_show_id_d9a7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['show', 'status'], name='bookings_sh_show_id_0a255a_idx'),
        ),
        migrations.AddConstraint(
            model_name='showseat',
            constraint=models.UniqueConstraint(fields=('show', 'seat'), name='unique_seat_per_show'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('booking', 'show_seat'), name='unique_booking_show_seat'),
        ),
    ]
