# Generated by Django 6.1.1 on 2026-09-20 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='tickets/%Y/%m/%d/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='bookings.booking')),
            ],
        ),
    ]
