# Generated by Django 6.0.8 on 2026-09-20 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_ticket'),
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showseat',
            options={'ordering': ['seat__row', 'seat__number']},
        ),
        migrations.RemoveConstraint(
            model_name='showseat',
            name='unique_seat_per_show',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_show_id_d9a7dc_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingseat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='showseat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='bookings_bo_status_86acff_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingseat',
            index=models.Index(fields=['booking'], name='bookings_bo_booking_458efe_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingseat',
            index=models.Index(fields=['show_seat'], name='bookings_bo_show_se_7431d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='showseat',
            constraint=models.UniqueConstraint(fields=('show', 'seat'), name='unique_show_seat'),
        ),
    ]
