# Generated by Django 6.0.8 on 2026-09-26 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_showseat_options_and_more'),
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AddField(
            model_name='showseat',
            name='held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_show_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showseat',
            name='held_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['show', 'held_until'], name='bookings_sh_show_id_fcc985_idx'),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['held_by', 'held_until'], name='bookings_sh_held_by_bcb56c_idx'),
        ),
    ]
