# Generated by Django 6.1.1 on 2026-09-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('rating', models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=3)),
                ('popularity', models.PositiveIntegerField(db_index=True, default=0)),
                ('poster', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
                ('languages', models.ManyToManyField(blank=True, related_name='movies', to='movies.language')),
            ],
            options={
                'ordering': ['-popularity', '-release_date'],
            },
        ),
    ]
