# Generated by Django 6.0.8 on 2026-09-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_castmember_movieposter_moviecast_moviereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_certification',
            field=models.CharField(blank=True, default='U', max_length=10),
        ),
    ]
